### ISSUE TITLE
Feature Request: RSS Feed

### ISSUE THREAD

**Issue by dwvisser** [DanielOliver/KnoxTechTrend#23]
I know analytics is your stated goal, but for me, it would be so awesome if the data you're pulling could be exposed as an RSS feed of upcoming meetings (with registration links).

**Comment by DanielOliver** [comment]
That would be pretty nice. I'm not a particularly big fan of Meetup's UI or bombarding with suggestions for unrelated things clogging up that feed.

Right now I'm just querying past meetups for simplicity's sake, but I'd love for some help to get that going.

https://github.com/DanielOliver/KnoxTechTrend/blob/e0a5270ef6a16fb7f2859cfd80c4ac105d2e1232/func/QueryMeetupEvents/index.js#L9

**Comment by dwvisser** [comment]
Appears to be a dead project now.
